export const players = [
    {
      fname: "SCOTT",
      lname: "CARSON",
      number: "33",
      src: "src/scott-carson.webp",
      position: "Goalkeeper",
      teamType: "Man",
    },
    {
      fname: "",
      lname: "EDERSON",
      number: "31",
      src: "src/ederson.webp",
      position: "Goalkeeper",
      teamType: "Man",
    },
    {
      fname: "STEFANORTEGA",
      lname: "MORENO",
      number: "18",
      src: "src/stefan-ortega-morenp.webp",
      position: "Goalkeeper",
      teamType: "Man",
    },
    {
      fname: "ZAKE",
      lname: "STEEFEN",
      number: "13",
      src: "src/zack-steffen.webp",
      position: "Goalkeeper",
      teamType: "Man",
    },
    {
      fname: "MANUEL",
      lname: "AKANJI",
      number: "25",
      src: "src/manuel-akanji.webp",
      position: "Defender",
      teamType: "Man",
    },
    {
      fname: "NATHAN",
      lname: "AKE",
      number: "6",
      src: "src/nathan-ake.webp",
      position: "Defender",
      teamType: "Man",
    },
    {
      fname: "JOÃO",
      lname: "CANCELO",
      number: "7",
      src: "src/joao-cancelo.webp",
      position: "Defender",
      teamType: "Man",
    },
    {
      fname: "RUBEN",
      lname: "DIAS",
      number: "3",
      src: "src/ruben-dias.webp",
      position: "Defender",
      teamType: "Man",
    },
    {
      fname: "SERGIO",
      lname: "GOMEZ",
      number: "21",
      src: "src/sergio-gomez.webp",
      position: "Defender",
      teamType: "Man",
    },
    {
      fname: "AYMERIC",
      lname: "LAPORTE",
      number: "14",
      src: "src/aymeric-laporte.webp",
      position: "Defender",
      teamType: "Man"
    },
    {
      fname: "RICO",
      lname: "LEWIS",
      number: "82",
      src: "src/rico-lewis.webp",
      position: "Defender",
      teamType: "Man",
    },
    {
      fname: "JOHN",
      lname: "STONES",
      number: "5",
      src: "src/john-stones.webp",
      position: "Defender",
      teamType: "Man",
    },
    {
      fname: "KYLE",
      lname: "WALKER",
      number: "2",
      src: "src/kyle-walker.webp",
      position: "Defender",
      teamType: "Man",
    },
    {
      fname: "JOSHUAWILSON-",
      lname: "ESBRAND",
      number: "97",
      src: "src/microsoftteams-image-36.webp",
      position: "Defender",
      teamType: "Man",
    },
    {
      fname: "KEVIN",
      lname: "DE BRUYNE",
      number: "17",
      src: "src/kevin-de-bruyne.webp",
      position: "Midfielder",
      teamType: "Man",
    },
    {
      fname: "PHIL",
      lname: "FODEN",
      number: "47",
      src: "src/phil-foden.webp",
      position: "Midfielder",
      teamType: "Man",
    },
    {
      fname: "JACK",
      lname: "GREALISH",
      number: "10",
      src: "src/jack-grealish.webp",
      position: "Midfielder",
      teamType: "Man",
    },
    {
      fname: "",
      lname: "RODRIGO",
      number: "16",
      src: "src/rodrigo.webp",
      position: "Midfielder",
      teamType: "Man",
    },
    {
      fname: "MATEO",
      lname: "KOVACIC",
      number: "8",
      src: "src/mateo-kovacic-profile.webp",
      position: "Midfielder",
      teamType: "Man",
    },
    {
      fname: "COLE",
      lname: "PALMER",
      number: "80",
      src: "src/cole-palmer.webp",
      position: "Midfielder",
      teamType: "Man",
    },
    {
      fname: "MAXIMO",
      lname: "PERRONE",
      number: "32",
      src: "src/maximo-perrone.webp",
      position: "Midfielder",
      teamType: "Man"
    },
    {
      fname: "KALVIN",
      lname: "PHILLIPS",
      number: "4",
      src: "src/kalvin-philips.webp",
      position: "Midfielder",
      teamType: "Man"
    },
    {
      fname: "BERNARDO",
      lname: "SILVA",
      number: "20",
      src: "src/bernardo-silva.webp",
      position: "Midfielder",
      teamType: "Man",
    },
    {
      fname: "JULIAN",
      lname: "ALVAREZ",
      number: "19",
      src: "src/julian-alvarez.webp",
      position: "Forward",
      teamType: "Man",
    },
    {
      fname: "ERLING",
      lname: "HAALAND",
      number: "9",
      src: "src/erling-haaland.webp",
      position: "Forward",
      teamType: "Man",
    },
  
    {
      fname: "RIYAD",
      lname: "MAHREZ",
      number: "26",
      src: "src/riyad-mahrez.webp",
      position: "Forward",
      teamType: "Man",
    },
    {
      fname: "PEP",
      lname: "GUARDIOLA",
      number: "",
      src: "src/pep-guardiola.webp",
      position: "Manager",
      teamType: "Man",
    },
    {
        fname: "KHIARA",
        lname: "KEATING",
        number: "35",
        src: "src/khiara-keating.webp",
        position: "Goalkeeper",
        teamType: "Woman",
      },
      {
        fname: "SANDY",
        lname: "MACIVER",
        number: "22",
        src: "src/sandy-maciver.webp",
        position: "Goalkeeper",
        teamType: "Woman",
      },
      {
        fname: "ELLIE",
        lname: "ROEBUCK",
        number: "1",
        src: "src/ellie-roebuck.webp",
        position: "Goalkeeper",
        teamType: "Woman",
      },
      {
        fname: "STEPH",
        lname: "HOUGHTON",
        number: "6",
        src: "src/steph-houghton.webp",
        position: "Defender",
        teamType: "Woman",
      },
      {
        fname: "LAIA",
        lname: "ALEIXANDRI",
        number: "4",
        src: "src/laia-aleixandri.webp",
        position: "Defender",
        teamType: "Woman",
      },
      {
        fname: "KERSTIN",
        lname: "CASPARIJ",
        number: "2",
        src: "src/kerstin-casparij.webp",
        position: "Defender",
        teamType: "Woman",
      },
      {
        fname: "ALEX",
        lname: "GREENWOOD",
        number: "5",
        src: "src/alex-greenwood.webp",
        position: "Defender",
        teamType: "Woman",
      },
      {
        fname: "ALANNA",
        lname: "KENNEDY",
        number: "33",
        src: "src/alanna-kennedy.webp",
        position: "Defender",
        teamType: "Woman",
      },
      {
        fname: "RUBY",
        lname: "MACE",
        number: "30",
        src: "src/ruby-mace.webp",
        position: "Defender",
        teamType: "Woman",
      },
      {
        fname: "ESME",
        lname: "MORGAN",
        number: "14",
        src: "src/esme-morgan.webp",
        position: "Defender",
        teamType: "Woman",
      },
      {
        fname: "LEILA",
        lname: "OUAHABI",
        number: "15",
        src: "src/leilaouahabi.webp",
        position: "Defender",
        teamType: "Woman",
      },
      {
        fname: "DEMI",
        lname: "STOKES",
        number: "3",
        src: "src/demi-stokes.webp",
        position: "Defender",
        teamType: "Woman",
      },
      {
        fname: "FILIPPA",
        lname: "ANGELDAHL",
        number: "12",
        src: "src/filippa-angeldahl.webp",
        position: "Midfielder",
        teamType: "Woman",
      },
      {
        fname: "JULIE",
        lname: "BLAKSTAD",
        number: "41",
        src: "src/julie-blakstad (1).webp",
        position: "Midfielder",
        teamType: "Woman",
      },
      {
        fname: "LAURA",
        lname: "COOMBS",
        number: "7",
        src: "src/laura-coombs.webp",
        position: "Midfielder",
        teamType: "Woman",
      },
      {
        fname: "YUI",
        lname: "HASEGAWA",
        number: "25",
        src: "src/yui-hasegawa.webp",
        position: "Midfielder",
        teamType: "Woman",
      },
      {
        fname: "DEYNA",
        lname: "CASTELLANOS",
        number: "10",
        src: "src/denya-castellanos.webp",
        position: "Forward",
        teamType: "Woman",
      },
      {
        fname: "MARY",
        lname: "FOWLER",
        number: "8",
        src: "src/mary-fowler.webp",
        position: "Forward",
        teamType: "Woman",
      },
      {
        fname: "LAUREN",
        lname: "HEMP",
        number: "11",
        src: "src/lauren-hemp.webp",
        position: "Forward",
        teamType: "Woman",
      },
      {
        fname: "CHLOE",
        lname: "KELLY",
        number: "9",
        src: "src/chloe-kelly.webp",
        position: "Forward",
        teamType: "Woman",
      },
      {
        fname: "JESS",
        lname: "PARK",
        number: "16",
        src: "src/jess-park.webp",
        position: "Forward",
        teamType: "Woman",
      },
      {
        fname: "KHADIJA",
        lname: "SHAW",
        number: "21",
        src: "src/khadija-shaw.webp",
        position: "Forward",
        teamType: "Woman",
      },
      {
        fname: "GARETH",
        lname: "TAYLOR",
        number: "",
        src: "src/gareth-taylor.webp",
        position: "Manager",
        teamType: "Woman",
      },
      {
        fname: "ALAN",
        lname: "MAHON",
        number: "",
        src: "src/alan-mahon.webp",
        position: "Assmanager",
        teamType: "Woman",
      },
      {
        fname: "CHRIS",
        lname: "WILLIAMS",
        number: "",
        src: "src/microsoftteams-image-14.webp",
        position: "Assmanager",
        teamType: "Woman",
      },
      {
        fname: "LORENZO",
        lname: "BUENAVENTURA",
        number: "",
        src: "src/lorenzo-buenaventura (1).webp",
        position: "Assmanager",
        teamType: "Man",
      },
      {
        fname: "MANEL",
        lname: "ESTIARTE",
        number: "",
        src: "src/manel-estiarte (1).webp",
        position: "Assmanager",
        teamType: "Man",
      },
      {
        fname: "XABIER",
        lname: "MANCISIDOR",
        number: "",
        src: "src/xabier-mancisidor (1).webp",
        position: "Assmanager",
        teamType: "Man",
      },
      {
        fname: "CARLES",
        lname: "PLANCHART",
        number: "",
        src: "src/carles-planchart.webp",
        position: "Assmanager",
        teamType: "Man",
      },
      {
        fname: "CARLOS",
        lname: "VICENS",
        number: "",
        src: "src/carlos-vicens.webp",
        position: "Assmanager",
        teamType: "Man",
      },
      {
        fname: "RICHARD",
        lname: "WRIGHT",
        number: "",
        src: "src/richard-wright (1).webp",
        position: "Assmanager",
        teamType: "Man",
      },
    //   {
    //     fname: "JOSH",
    //     lname: "MCNAMARA",
    //     number: "",
    //     src: "src/josh-mcnamara.webp",
    //     position: "Goalkeeper",
    //     teamType: "Eds",
    //   },
    //   {
    //     fname: "MIKKI",
    //     lname: "VAN SAS",
    //     number: "",
    //     src: "src/new-mikki-van-sas.webp",
    //     position: "Goalkeeper",
    //     teamType: "Eds",
    //   },
    //   {
    //     fname: "JADEL",
    //     lname: "KATONGO",
    //     number: "",
    //     src: "src/jadel-katongo.webp",
    //     position: "Defender",
    //     teamType: "Eds",
    //   },
      {
        fname: "LUKE",
        lname: "MBETE",
        number: "",
        src: "src/luke-mbete.webp",
        position: "Defender",
        teamType: "Eds",
      },
    //   {
    //     fname: "ISAAC",
    //     lname: "SMITH",
    //     number: "",
    //     src: "src/isaac-smith.webp",
    //     position: "Defender",
    //     teamType: "Eds",
    //   },
      {
        fname: "JOSH",
        lname: "ADAM",
        number: "",
        src: "src/josh-adam.webp",
        position: "Midfielder",
        teamType: "Eds",
      },
      {
        fname: "OSCAR",
        lname: "BOBB",
        number: "",
        src: "src/oscar-bobb.webp",
        position: "Midfielder",
        teamType: "Eds",
      },
      {
        fname: "KIAN",
        lname: "BRECKIN",
        number: "",
        src: "src/kian-breckin.webp",
        position: "Midfielder",
        teamType: "Eds",
      },
    //   {
    //     fname: "",
    //     lname: "",
    //     number: "",
    //     src: "",
    //     position: "Midfielder",
    //     teamType: "Eds",
    //   },
      
      
     

  ];